src/Makevars.win
=> Fix parallel build

.Rbuildignore, .github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/security.md, CODE_OF_CONDUCT.md, DESCRIPTION, LICENSE.md, README.md, _pkgdown.yml
- rules for contributing
- license LGPL 2.1.
- template for issue contribution
- code of conduct
- http -> https where possible and update of some links
- method for security vulnerability reports
=> CII requirements

src/MariaBinding.cpp, src/MariaBinding.h, tests/testthat/test-queries.R
=> Support fractional seconds in datetime values

NEWS.md, cran-comments.md
=> CRAN release v1.0.10

NEWS.md, README.md, cran-comments.md
=> RMariaDB 1.0.11

R/coerce.R, R/query.R
=> Fix dbBind() for date values of mode integer

R/table.R, src/MariaResultPrep.cpp, src/MariaRow.cpp, src/MariaTypes.cpp, src/MariaTypes.h
=> BIT(1) columns come back as logical

.github/workflows/R-CMD-check-dev.yaml, .github/workflows/R-CMD-check.yaml, .github/workflows/test-coverage.yaml, DESCRIPTION, R/MariaDBConnection.R, R/MariaDBResult.R, R/coerce.R, R/connect.R, R/default.R, R/query.R, R/table.R, man/dbConnect-MariaDBDriver-method.Rd, src/MariaBinding.cpp, tests/testthat/test-DBItest.R, tests/testthat/test-queries.R, tests/testthat/test-timezone.R
- Add timezone_out argument
- Fix writing timestamp values with non-UTC time zone
- Support timezone = NULL argument
Closes #116.
=> Fix timezone handling

.Rbuildignore, NEWS.md, cran-comments.md
=> CRAN release v1.1.0

src/MariaRow.cpp, src/MariaRow.h, tests/testthat/test-queries.R
=> Map NULL to NA for bit(1) columns

.Rbuildignore, NEWS.md, cran-comments.md, tests/testthat/test-queries.R
=> CRAN release v1.1.1

R/table.R, src/MariaBinding.cpp
=> TIME and DATETIME use microsecond precision by default

.github/workflows/R-CMD-check.yaml
=> Test combinations of MariaDB client and server

DESCRIPTION, README.md, configure
in documentation and scripts. Closes #219.
=> Refer to libmariadb-dev

NEWS.md, cran-comments.md
=> CRAN release v1.1.2

tests/testthat/helper-DBItest.R
=> Update for DBItest 1.7.2

tests/testthat/helper-DBItest.R
=> Enable test

.github/workflows/R-CMD-check.yaml
=> Fix workflows

_pkgdown.yml
=> Add reference index

.github/workflows/R-CMD-check.yaml
=> Parallel Windows testing

DESCRIPTION, R/query.R
=> Return blob objects

src/DbConnection.cpp, src/DbConnection.h, src/MariaResultPrep.cpp
=> Minor code tweaks

tests/testthat/test-dbWriteTable.R
=> Test writing JSON columns

NEWS.md, README.md, cran-comments.md
=> CRAN release v1.2.0

.github/workflows/custom/before-install/action.yml, src/Makevars.ucrt, src/Makevars.win
=> Windows: upgrade to mariadb-connector-c 3.2.5

DESCRIPTION, R/MariaDBConnection.R, R/MariaDBResult.R, R/default.R, R/query.R, R/table.R, R/transaction.R, tests/testthat/test-DBItest.R, tests/testthat/test-dbWriteTable.R, tests/testthat/test-queries.R
=> Enable auto-styling

NEWS.md, cran-comments.md
=> CRAN release v1.2.1

src/DbConnection.cpp
=> Actually enable LOAD LOCAL INFILE

R/dbQuoteIdentifier_MariaDBConnection_Id.R
=> Support Id(catalog =) if the value is def everywhere

DESCRIPTION, R/dbAppendTable_MariaDBConnection.R, R/table.R, tests/testthat/test-dbWriteTable.R
Closes #253 
This will work if the upstream https://github.com/r-dbi/DBI/pull/381 is also merged.
=> feat: `dbAppendTable()` accepts `Id`

DESCRIPTION
=> Get rid of remote

NEWS.md, cran-comments.md
=> CRAN release v1.2.2

DESCRIPTION, tests/testthat.R, tests/testthat/test-astyle.R, tests/testthat/test-dbWriteTable.R, tests/testthat/test-queries.R
=> feat: Use testthat edition 3

.github/workflows/R-CMD-check.yaml, src/Makevars.ucrt, src/Makevars.win, tools/winlibs.R
Adds support for building on arm64 on Windows.
=> chore: Update Windows libs to new location

src/MariaTypes.cpp, tests/testthat/test-dbWriteTable.R
=> fix: Return JSON as string on MySQL

.github/workflows/custom/after-install/action.yml
=> chore: Upgrade MariaDB on CI/CD

tests/testthat/helper-DBItest.R, tests/testthat/test-DBItest.R
=> test: Skip tests if packages are not available

src/MariaTypes.cpp
=> Fix compilation on CentOS 7

.Rbuildignore, DESCRIPTION, NEWS.md, README.md, cran-comments.md
=> CRAN release v1.3.0

R/connect.R, man/Client-flags.Rd
=> docs: Update docs for client flags

DESCRIPTION, NEWS.md, README.md, cran-comments.md
- Groom `NEWS.md` and `cran-comments.md`
- Wait for successful tests
- If needed, tweak and review PR
- Run `fledge::release()`
- Confirm CRAN e-mail
- When the package is accepted on CRAN, run `fledge::post_release()` (often handled by GitHub Actions)
=> CRAN release v1.3.2
